# Generated by Django 5.1.4 on 2025-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orders_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
